# Generated by Django 4.2.10 on 2024-02-12 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("arrive_dt", models.DateTimeField(verbose_name="arrival date")),
                ("depart_dt", models.DateTimeField(verbose_name="departure date")),
                ("lodging", models.CharField(max_length=200)),
                ("notes", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200)),
                ("item_type", models.CharField(max_length=200)),
                ("cost", models.IntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
                    ),
                ),
            ],
        ),
    ]
