# Generated by Django 4.2.10 on 2024-02-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("f", "food"),
                    ("l", "lodging"),
                    ("t", "transportation"),
                    ("e", "entertainment"),
                    ("o", "other"),
                ],
                max_length=200,
            ),
        ),
    ]
