# Generated by Django 4.2.10 on 2024-02-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_budget_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="country",
            field=models.CharField(default="US", max_length=200),
        ),
    ]
