# Generated by Django 4.2.10 on 2024-02-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline", models.CharField(max_length=200)),
                ("airports", models.CharField(max_length=200)),
                ("arrive_time", models.DateTimeField(verbose_name="time of flight")),
                ("depart_time", models.DateTimeField(verbose_name="time of return")),
                ("notes", models.CharField(max_length=200, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200, null=True)),
                ("type", models.CharField(max_length=200)),
                ("notes", models.CharField(max_length=200, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
                    ),
                ),
            ],
        ),
    ]
