# Generated by Django 4.2.10 on 2024-02-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_attraction_confirmed_attraction_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("f", "food"),
                    ("l", "lodging"),
                    ("t", "transportation"),
                    ("e", "entertainment"),
                    ("o", "other"),
                ],
                default=("f", "food"),
                max_length=200,
            ),
        ),
    ]
